steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - notificacao_pubsub
  - --source=.
  - --trigger-topic=notificacao_pubsub
  - --runtime=nodejs18
  - --allow-unauthenticated
